### ISSUE TITLE
[Raspberry] Pexpect error

### ISSUE THREAD

**Issue by rubencabrera** [rubencabrera/vim#3]
Al ejecutar el instalar.py, cuando llega a la parte de instalar los paquetes con apt-get:

```
Traceback (most recent call last):
  File "./instalar.py", line 57, in <module>
    child.expect("password")
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 105, in expect_loop
    return self.eof(e)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 50, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x76a93f50>
command: /usr/bin/sudo
args: ['/usr/bin/sudo', 'apt-get', 'install', 'build-essential', 'cmake', 'python-dev', 'python3-dev', '-y']
buffer (last 100 chars): ''
before (last 100 chars): 'reciente (3.5.3-1).\r\n0 actualizados, 0 nuevos se instalar\xc3\xa1n, 0 para eliminar y 1 no actualizados.\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 4543
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: <open file '<stdout>', mode 'w' at 0x76d38078>
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("password")
```

**Comment by rubencabrera** [comment]
La dependencia de pexpect parece estar bien. Versión según pip freeze: pexpect==4.2.1
